// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// function Bottle(props) {
//   const { nodes, materials } = useGLTF('/Infinix Water Bottle.glb')
//   return (
//     <group {...props} dispose={null}>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bottle.geometry}
//         material={materials['Material.001']}
//         position={[0, 3.14, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle.geometry}
//           material={materials['Material.002']}
//           position={[0, 4.099, 0]}
//           scale={[1, 0.492, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle001.geometry}
//           material={materials['Material.004']}
//           position={[0.055, 4.097, 0.029]}
//           scale={[0.027, 0.058, 0.027]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder001.geometry}
//           material={materials['Material.001']}
//           position={[0, 3.622, 0]}
//           scale={[1, 0.473, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder002.geometry}
//           material={materials['Material.003']}
//           position={[0, 3.102, 0]}
//           scale={[0.962, 0.165, 0.962]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text.geometry}
//           material={materials['Material.004']}
//           position={[-0.059, 4.095, 0.004]}
//           rotation={[0, -1.571, 0]}
//           scale={0.473}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text001.geometry}
//           material={materials['Material.006']}
//           position={[-1, 0.743, 0.096]}
//           rotation={[Math.PI, 0, Math.PI / 2]}
//           scale={[1.718, 1, 1.208]}
//         />
//       </mesh>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bottle001.geometry}
//         material={materials['Material.001']}
//         position={[0, 1.052, 4.519]}
//         rotation={[0, 0, Math.PI / 2]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle002.geometry}
//           material={materials['Material.002']}
//           position={[0, 4.099, 0]}
//           scale={[1, 0.492, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle003.geometry}
//           material={materials['Material.004']}
//           position={[0.055, 4.097, 0.029]}
//           scale={[0.027, 0.058, 0.027]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder003.geometry}
//           material={materials['Material.001']}
//           position={[0, 3.622, 0]}
//           scale={[1, 0.473, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder004.geometry}
//           material={materials['Material.003']}
//           position={[0, 3.102, 0]}
//           scale={[0.962, 0.165, 0.962]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text002.geometry}
//           material={materials['Material.004']}
//           position={[-0.059, 4.095, 0.004]}
//           rotation={[0, -1.571, 0]}
//           scale={0.473}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text003.geometry}
//           material={materials['Material.006']}
//           position={[-1, 0.743, 0.096]}
//           rotation={[Math.PI, 0, Math.PI / 2]}
//           scale={[1.718, 1, 1.208]}
//         />
//       </mesh>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bottle002.geometry}
//         material={materials['Material.001']}
//         position={[1.92, 3.14, -2.333]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle004.geometry}
//           material={materials['Material.002']}
//           position={[0, 4.099, 0]}
//           scale={[1, 0.492, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle005.geometry}
//           material={materials['Material.004']}
//           position={[0.055, 4.097, 0.029]}
//           scale={[0.027, 0.058, 0.027]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder005.geometry}
//           material={materials['Material.001']}
//           position={[0, 3.622, 0]}
//           scale={[1, 0.473, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder006.geometry}
//           material={materials['Material.003']}
//           position={[0, 3.102, 0]}
//           scale={[0.962, 0.165, 0.962]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text004.geometry}
//           material={materials['Material.004']}
//           position={[-0.059, 4.095, 0.004]}
//           rotation={[0, -1.571, 0]}
//           scale={0.473}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text005.geometry}
//           material={materials['Material.006']}
//           position={[-1, 0.743, 0.096]}
//           rotation={[Math.PI, 0, Math.PI / 2]}
//           scale={[1.718, 1, 1.208]}
//         />
//       </mesh>
//       <mesh
//         castShadow
//         receiveShadow
//         geometry={nodes.Bottle003.geometry}
//         material={materials['Material.001']}
//         position={[1.92, 3.14, 2.199]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle006.geometry}
//           material={materials['Material.002']}
//           position={[0, 4.099, 0]}
//           scale={[1, 0.492, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Circle007.geometry}
//           material={materials['Material.004']}
//           position={[0.055, 4.097, 0.029]}
//           scale={[0.027, 0.058, 0.027]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder007.geometry}
//           material={materials['Material.001']}
//           position={[0, 3.622, 0]}
//           scale={[1, 0.473, 1]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Cylinder008.geometry}
//           material={materials['Material.003']}
//           position={[0, 3.102, 0]}
//           scale={[0.962, 0.165, 0.962]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text006.geometry}
//           material={materials['Material.004']}
//           position={[-0.059, 4.095, 0.004]}
//           rotation={[0, -1.571, 0]}
//           scale={0.473}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Text007.geometry}
//           material={materials['Material.006']}
//           position={[-1, 0.743, 0.096]}
//           rotation={[Math.PI, 0, Math.PI / 2]}
//           scale={[1.718, 1, 1.208]}
//         />
//       </mesh>
//     </group>
//   )
// }

// export default Bottle

// useGLTF.preload('/Infinix Water Bottle.glb')